-- Chạy một lần trong Supabase SQL Editor. Không xóa hay sửa bảng của Sàn Skill.
create table if not exists public.financial_twin_orders (
  id bigint generated by default as identity primary key,
  ma_don text not null,
  device_id text not null,
  plan text not null check (plan in ('pro_monthly', 'pro_yearly')),
  so_tien_vnd bigint not null check (so_tien_vnd in (79000, 690000)),
  so_ngay integer not null check (so_ngay in (30, 365)),
  trang_thai text not null default 'cho_thanh_toan',
  noi_dung_chuyen_khoan text not null,
  het_han_luc timestamptz not null,
  thanh_toan_luc timestamptz,
  pro_den timestamptz,
  sepay_transaction_id bigint,
  sepay_reference_code text,
  created_at timestamptz not null default now()
);

create unique index if not exists financial_twin_orders_ma_don_uidx on public.financial_twin_orders (ma_don);
create unique index if not exists financial_twin_orders_sepay_uidx on public.financial_twin_orders (sepay_transaction_id) where sepay_transaction_id is not null;
create index if not exists financial_twin_orders_device_idx on public.financial_twin_orders (device_id, pro_den desc);
create index if not exists financial_twin_orders_status_idx on public.financial_twin_orders (trang_thai);
alter table public.financial_twin_orders enable row level security;

alter table public.financial_twin_orders add column if not exists user_id uuid;
alter table public.financial_twin_orders add column if not exists user_email text;
create index if not exists financial_twin_orders_user_idx on public.financial_twin_orders (user_id, pro_den desc);

-- Nâng cấp bảng giá 39.000đ/tháng và 399.000đ trọn đời; giữ gói cũ để xử lý các đơn đã tạo trước đó.
alter table public.financial_twin_orders drop constraint if exists financial_twin_orders_plan_check;
alter table public.financial_twin_orders drop constraint if exists financial_twin_orders_so_tien_vnd_check;
alter table public.financial_twin_orders drop constraint if exists financial_twin_orders_so_ngay_check;
alter table public.financial_twin_orders add constraint financial_twin_orders_plan_check check (plan in ('pro_monthly', 'pro_yearly', 'pro_lifetime'));
alter table public.financial_twin_orders add constraint financial_twin_orders_so_tien_vnd_check check (so_tien_vnd in (39000, 79000, 399000, 690000));
alter table public.financial_twin_orders add constraint financial_twin_orders_so_ngay_check check (so_ngay in (30, 365, 36500));
