-- Chạy một lần trong Supabase SQL Editor. Không xóa hay sửa bảng của Sàn Skill.
create table if not exists public.financial_twin_orders (
  id bigint generated by default as identity primary key,
  ma_don text not null,
  device_id text not null,
  plan text not null check (plan in ('pro_monthly', 'pro_yearly')),
  so_tien_vnd bigint not null check (so_tien_vnd in (79000, 690000)),
  so_ngay integer not null check (so_ngay in (30, 365)),
  trang_thai text not null default 'cho_thanh_toan',
  noi_dung_chuyen_khoan text not null,
  het_han_luc timestamptz not null,
  thanh_toan_luc timestamptz,
  pro_den timestamptz,
  sepay_transaction_id bigint,
  sepay_reference_code text,
  created_at timestamptz not null default now()
);

create unique index if not exists financial_twin_orders_ma_don_uidx on public.financial_twin_orders (ma_don);
create unique index if not exists financial_twin_orders_sepay_uidx on public.financial_twin_orders (sepay_transaction_id) where sepay_transaction_id is not null;
create index if not exists financial_twin_orders_device_idx on public.financial_twin_orders (device_id, pro_den desc);
create index if not exists financial_twin_orders_status_idx on public.financial_twin_orders (trang_thai);
alter table public.financial_twin_orders enable row level security;
